name: inteligencia_forestal
description: "Aplicación móvil para manejo y sanidad forestal."

# Evita que el proyecto se publique accidentalmente en pub.dev
publish_to: 'none'

# Versión de la aplicación (versión + número de build)
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# -------------------------------
# DEPENDENCIAS PRINCIPALES
# -------------------------------
dependencies:
  flutter:
    sdk: flutter
  # Base de datos SQLite local
  sqflite: ^2.3.0
  path: ^1.8.3

  # Generación de identificadores únicos universales
  uuid: ^4.5.1

  #Formateo de fechas
  intl: ^0.18.1

  # Detecta si hay conexión a Internet (WiFi, datos móviles, sin conexión)
  connectivity_plus: ^6.0.4

  # Peticiones HTTP
  http: ^1.2.0

  # Permite usar tipografías de Google fácilmente (Roboto, Montserrat, etc.)
  google_fonts: ^6.2.1

  # Iconos estilo iOS (útiles si haces pantallas con estilo Cupertino)
  cupertino_icons: ^1.0.8

  # Carga imágenes desde URL con caché local (optimiza rendimiento)
  cached_network_image: ^3.4.1

  # Renderiza archivos SVG dentro de Flutter
  flutter_svg: ^2.0.10+1

  # Diseño responsivo en porcentaje (ancho/alto dinámico)
  sizer: ^2.0.15

  # Manejo de permisos del dispositivo (cámara, GPS, almacenamiento)
  permission_handler: ^11.3.1

  # Notificaciones tipo “toast” en Android/iOS
  fluttertoast: ^8.2.2

# -------------------------------
# DEPENDENCIAS PARA DESARROLLO
# -------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Reglas de estilo para mantener código ordenado y legible
  flutter_lints: ^5.0.0

# -------------------------------
# CONFIGURACIÓN DE FLUTTER
# -------------------------------
flutter:

  # Habilita el uso de Material Icons
  uses-material-design: true

  # Aquí puedes registrar tus assets (imágenes, JSON, etc.)
  # assets:
  #   - assets/images/
  #   - assets/data/

  # Para registrar fuentes personalizadas:
  # fonts:
  #   - family: MiFuente
  #     fonts:
  #       - asset: assets/fonts/MiFuente-Regular.ttf
